name: GemstonePlugin
version: '1.3'
main: me.vihaanvp.gemstoneplugin.GemstonePlugin
api-version: '1.21'
authors: [VihaanVP]
description: A Gemstone Plugin made for the Gemlands SMP, with 5 custom Gemstones and one SUPER Gemstone!

commands:
  givegem:
    description: Gives a specified gemstone to a player
    usage: /givegem <blazite|aquaryte|terranox|voltaryn|noctyra> [player]
    permission: gemstones.givegem

  giverandomizer:
    description: Gives a Gemstone Randomizer item to a player
    usage: /giverandomizer <amount> [player]
    permission: gemstones.giverandomizer

  givelootbox:
    description: Gives a Loot Box item to a player
    usage: /givelootbox <player>
    permission: gemstones.givelootbox

  deathdebuff:
    description: Apply or remove death debuff from a player.
    usage: /deathdebuff <remove|apply> [player]
    permission: gemstone.deathdebuff

  givebinder:
    description: Gives you a Gemstone Binder
    usage: /givebinder <amount> [player]
    permission: gemstones.givebinder

  giverevivebook:
    description: Gives you a revive book
    usage: /giverevivebook <amount> [player]
    permission: gemstones.giverevivebook

  reloadrevivefile:
    description: Reloads the revive file
    usage: /reloadrevivefile
    permission: gemstones.reloadrevivefile

  removedeathban:
    description: Remove deathban for a player
    usage: /removedeathban <player>
    permission: gemstones.deathban.remove

  deathban:
    description: Apply deathban for a player
    usage: /deathban <player>
    permission: gemstones.deathban

permissions:
  gemstones.givegem:
    description: Allows players to execute the /givegem command
    default: op

  gemstones.giverandomizer:
    description: Allows players to execute the /giverandomizer command
    default: op

  gemstones.givelootbox:
    description: Allows players to execute the /givelootbox command
    default: op

  gemstones.deathdebuff:
    description: Allows players to execute the /deathdebuff command
    default: op

  gemstones.givebinder:
    description: Allows players to execute the /givebinder command
    default: op

  gemstones.giverevivebook:
    description: Allows players to execute the /giverevivebook command
    default: op

  gemstones.reloadrevivefile:
    description: Allows players to execute the /reloadrevivefile command
    default: op

  gemstones.deathban:
    description: Allows players to execute the /deathban command
    default: op

  gemstones.deathban.remove:
    description: Allows players to execute the /removedeathban command
    default: op

  gemstones.deathban.bypass:
    description: Allows players to bypass the deathban so they will never get deathbanned
    default: op